
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbnews?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: edu.hfut.hawk_eye.entity


logging:
  level:
    com:
      example:
        mapper : debug

